name: Self-test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Run the action
        uses: mindbox-cloud/gha-release-number@Avdeev/BumpActionCore
        id: release-number
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
