name: Self-test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Run the action
        uses: mindbox-moscow/GHA-ReleaseNumber@v1.0.0
        id: release-number        
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
